const Entity = require('./Entity');

/**
 * @typedef {object} Calification
 * @property {String} entityID - where entity is the name of the key.
 * @property {Number} calif - the calification for this element.
 */

 /**
 * @typedef {object} OtherPonderation
 * @property {String} name - the name of the additional ponderation.
 * @property {Number} calif - the calification for that ponderation.
 */

class Califications extends Entity {

    /**
     * @property {Number} [semesterCalif = 0] - the calification of the semester
     * will be generated by the computation of the average of the califications 
     * of each subject of that semester.
     * @property {Calification[]} subjectsCalif - an array of the califications 
     * of each subject.
     * @property {Calification[]} modulesCalif - an array of the califications 
     * for each module of each subject.
     * @property {Calification[]} activitiesCalif - an array of the
     * califications of each activitie of each module of each subject.
     * @property {OtherPonderation[]} otherPonderations - an array of the
     * califications of the aditional pondetations that the user creates.
     */

    /**
     * An object representing the califications of a specific user.
     * @param {String} userID - the system generated key for the user to wich
     * this clacifications belongs.
     * @param {String} semesterID - the system generated key for the semester to 
     * wich this califications belongs.
     */
    constructor(userID, semesterID) {
        super('calif'); //califID: String
        this.userID = userID;
        this.semesterID = semesterID;
        this.semesterCalif = 0;

        //default properties.
        this.subjectsCalif = [];
        this.modulesCalif = [];
        this.activitiesCalif = [];
        this.otherPonderations = [];
    }
}

module.exports = Califications;