const { genRandomKey } = require('../../util/generators');

class Entity {
    /**
     * This object generates an identifier for an specific entity.
     * @param {String} ideitifier - the ID's of this system are generated by the
     * name of the entity to wich this ID belongs added to the string 'ID'. Then
     * , if you pass as the parameter for the identifier 'subject'. the property
     * designed to identify this object will be 'subjectID'. 
     * @param {Number} idLength - the length of the random ID.
     */
    constructor(ideitifier, idLength = 6) {
        this[`${ideitifier}ID`] = genRandomKey(idLength);
    }
}

module.exports = Entity;